# Generated by Django 6.0.3 on 2026-04-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatparticipation',
            table='chats_participation',
        ),
    ]
