# Generated by Django 6.0.3 on 2026-05-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0002_remove_identity_key_agreement_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.identity'),
        ),
    ]
