# Generated by Django 6.0.3 on 2026-05-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_signature_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='signature',
            field=models.TextField(),
        ),
    ]
