# Generated by Django 6.0.3 on 2026-05-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='key_agreement_signature',
        ),
    ]
