# Generated by Django 6.0.3 on 2026-04-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='key_agreement_public_key',
            field=models.CharField(default='pending', max_length=255),
            preserve_default=False,
        ),
    ]
